/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "messages": {
            "loginSuccess": string;
            "registerSuccess": string;
            "passwordResetSuccess": string;
            "logoutSuccess": string;
            "allSessionsLoggedOut": string;
            "sessionLoggedOut": string;
            "verificationEmailSent": string;
            "resetPasswordEmailSent": string;
            "emailVerified": string;
        };
        "exceptions": {
            "invalidCredentials": string;
            "registrationFailed": string;
            "sessionExpired": string;
            "userNotFound": string;
            "emailAlreadyExists": string;
            "userAlreadyVerified": string;
            "userBlocked": string;
        };
        "validation": {
            "loginDto": {
                "email": {
                    "isString": string;
                    "isNotEmpty": string;
                };
                "password": {
                    "isString": string;
                    "isNotEmpty": string;
                };
            };
            "logoutSessionsDto": {
                "sessionIds": {
                    "isUUID": string;
                };
            };
            "registerDto": {
                "email": {
                    "isString": string;
                    "isNotEmpty": string;
                };
                "password": {
                    "isString": string;
                    "isNotEmpty": string;
                };
                "name": {
                    "isString": string;
                    "isNotEmpty": string;
                };
            };
            "resendEmailDto": {
                "email": {
                    "isString": string;
                    "isNotEmpty": string;
                };
            };
            "resetPasswordDto": {
                "password": {
                    "isString": string;
                    "isNotEmpty": string;
                };
                "confirmPassword": {
                    "isString": string;
                    "isNotEmpty": string;
                    "isMatch": string;
                };
            };
            "sendRestPasswordDto": {
                "email": {
                    "isString": string;
                    "isNotEmpty": string;
                };
            };
            "tokenDto": {
                "token": {
                    "isString": string;
                    "isNotEmpty": string;
                };
            };
        };
    };
    "user": {
        "validation": {
            "name": {
                "description": string;
                "isString": string;
                "isNotEmpty": string;
            };
            "email": {
                "description": string;
                "isEmail": string;
                "isNotEmpty": string;
            };
            "password": {
                "description": string;
                "isString": string;
                "isNotEmpty": string;
                "minLength": string;
            };
            "role": {
                "description": string;
                "isEnum": string;
                "isNotEmpty": string;
            };
            "status": {
                "description": string;
                "isEnum": string;
                "isNotEmpty": string;
            };
        };
        "message": {
            "findSuccess": string;
            "findAllSuccess": string;
            "createSuccess": string;
            "updateSuccess": string;
            "deleteSuccess": string;
            "hardDeleteSuccess": string;
            "restoreSuccess": string;
        };
        "exception": {
            "notFound": string;
            "emailAlreadyExists": string;
            "notSoftDeleted": string;
            "errorDelete": string;
            "alreadySoftDeleted": string;
            "alreadyVerified": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
